name: Test, Build & Release

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test_build_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 'Test'
        run: yarn test

      - name: 'Authenticate with npm registry'
        if: env.BRANCH_NAME == 'master'
        run: |
          echo "//registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}" >> "${HOME}/.npmrc"
          git config --global user.email webapp+travis@wire.com
          git config --global user.name "Wire Travis CI"

      - name: 'Release'
        if: env.BRANCH_NAME == 'master'
        run: yarn version --minor
