name: Test, Build & Release

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test_build_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v2

      - name: 'Extend environment variables'
        run: |
          echo "BRANCH_NAME=$(git branch --show-current)" >> $GITHUB_ENV

      - name: 'Build & Test'
        run: yarn && yarn dist && yarn test

      - name: 'Authenticate with GitHub (to commit new tag)'
        if: env.BRANCH_NAME == 'master'
        env:
          GH_TOKEN: ${{secrets.OTTO_THE_BOT_GH_TOKEN}}
        run: echo -e "machine github.com\n  login ${GH_TOKEN}" > ~/.netrc

      - name: 'Authenticate with npm registry (to publish new version)'
        if: env.BRANCH_NAME == 'master'
        run: |
          echo "//registry.npmjs.org/:_authToken=${{secrets.WEBTEAM_NPM_TOKEN}}" >> "${HOME}/.npmrc"
          git config --global user.email webapp+travis@wire.com
          git config --global user.name "Wire Travis CI"

      - name: 'Release new version'
        if: env.BRANCH_NAME == 'master'
        run: yarn version --minor

  run-ios-spm-tests:
    name: Test Swift package on macOS
    runs-on: macos-15

    steps:
      - name: Install swift-protobuf
        run: brew install swift-protobuf

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Ensure generated code is up-to-date
        run: |
          set -Eeuo pipefail
          cd ios
          ./update.sh

          if ! git diff --quiet; then       # returns non-zero when there are changes
            echo "::error::Generated Swift sources are OUT OF DATE."
            echo "Run the generator locally and commit the results."
            echo    # blank line for readability
            git --no-pager diff             # show the diff in the log (optional)
            exit 1
          fi

      - name: Run tests
        run: |
          xcodebuild \
            -workspace . \
            -scheme GenericMessageProtocol \
            -destination "platform=macOS,arch=arm64" \
            -quiet \
            clean test
